import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { Header } from '@/components/header';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Mentoras',
  description: 'Generated by create next app',
};

type RootProps = Readonly<{ children: React.ReactNode }>;

export default function RootLayout({ children }: RootProps) {
  return (
    <html lang="pt-BR">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased dark font-[family-name:var(--font-geist-sans)]`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
